# Add application configuration variables here, as shown below.

defaults: &defaults
  # Settings
  DINGO_EMAIL: dingo@dingoapp.co.uk
  DINGO_LOGO: http://dingoapp.bitnamiapp.com/web/wp-content/uploads/2013/04/App-Logo3-80x80.png
  DINGO_USER_ID: "32"
  EVENTS_LIMIT: "200"
  MESSAGES_LIMIT: "200"
  OFFERS_LIMIT: "200"
  TICKETS_LIMIT: "200"
  
  # Amazon S3
  AWS_BUCKET: dingoapp-test
  AWS_KEY: aws-key
  AWS_SECRET: aws-secret
  # Apple Push Notifications
  APN_HOST: gateway.push.apple.com   #gateway.sandbox.push.apple.com
  APN_PORT: "2195"
  APN_PEM_FILE: app/assets/certificates/certProd.pem #certDev.pem
  APN_PASSWORD: apn-password
  # Android Push Notifications
  GCM_HOST: https://android.googleapis.com/gcm/send
  GCM_KEY: gcm-key
  # Paypal API
  PAYPAL_MODE: sandbox
  # Paypal Rest API Credentials
  PAYPAL_ENDPOINT: api.sandbox.paypal.com
  PAYPAL_CLIENTID: paypalId
  PAYPAL_SECRET: paypalSecret
  # Paypal Classic API Credentials
  PAYPAL_APP_ID: APP-80W284485P519543T
  PAYPAL_USERNAME: phil-facilitator_api1.dingoapp.co.uk
  PAYPAL_PASSWORD: "paypalPassword"
  PAYPAL_SIGNATURE: paypalSignature
  # Stripe API
  STRIPE_TEST_SECRET_KEY: st_test_key
  STRIPE_LIVE_SECRET_KEY: sk_live_key
  
development:
  <<: *defaults
  
test:
  <<: *defaults
  
production:
  <<: *defaults
  # Amazon S3
  AWS_BUCKET: dingoapp-prod
  AWS_KEY: awsKey
  AWS_SECRET: awsSecret
  
  # Apple Push Notifications
  APN_HOST: gateway.push.apple.com
  APN_PORT: "2195"
  APN_PEM_FILE: app/assets/certificates/certProd.pem
  APN_PASSWORD: apnPasswd

  # Paypal API
  PAYPAL_MODE: live
  PAYPAL_ENDPOINT: api.paypal.com
  
  # Paypal Classic API Credentials
  PAYPAL_APP_ID: APP-ID
  PAYPAL_USERNAME: phil_api1.dingoapp.co.uk
  PAYPAL_PASSWORD: paypalPasswd
  PAYPAL_SIGNATURE: paypalSignature

